sudo: false
language: java
jdk:
  - oraclejdk11

notifications:
  email: false

before_deploy:
  - mvn clean
  - zip -r ${TRAVIS_TAG}.zip target/*.jar

after_success:
  - echo "<settings><servers><server><id>nexus-snapshots</id><username>\${CLI_DEPLOY_USERNAME}</username> <password>\${CLI_DEPLOY_PASSWORD}</password></server></servers></settings>" > ~/settings.xml
  - if [ -z ${TRAVIS_TAG} ]; then mvn deploy -DskipTests --settings ~/settings.xml; fi

deploy:
  provider: releases
  file: ${TRAVIS_TAG}.zip
  on:
    branch: master
    tags: true